package com.pgmmers.radar.vo.data;

import java.util.Date;

public class MobileInfoVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MOBLE_INFO.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MOBLE_INFO.MOBILE
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MOBLE_INFO.PROVINCE
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MOBLE_INFO.CITY
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MOBLE_INFO.SUPPLIER
     *
     * @mbggenerated
     */
    private String supplier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MOBLE_INFO.REGION_CODE
     *
     * @mbggenerated
     */
    private String regionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MOBLE_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_MOBLE_INFO.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MOBLE_INFO.ID
     *
     * @return the value of DATA_MOBLE_INFO.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MOBLE_INFO.ID
     *
     * @param id the value for DATA_MOBLE_INFO.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MOBLE_INFO.MOBILE
     *
     * @return the value of DATA_MOBLE_INFO.MOBILE
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MOBLE_INFO.MOBILE
     *
     * @param mobile the value for DATA_MOBLE_INFO.MOBILE
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MOBLE_INFO.PROVINCE
     *
     * @return the value of DATA_MOBLE_INFO.PROVINCE
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MOBLE_INFO.PROVINCE
     *
     * @param province the value for DATA_MOBLE_INFO.PROVINCE
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MOBLE_INFO.CITY
     *
     * @return the value of DATA_MOBLE_INFO.CITY
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MOBLE_INFO.CITY
     *
     * @param city the value for DATA_MOBLE_INFO.CITY
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MOBLE_INFO.SUPPLIER
     *
     * @return the value of DATA_MOBLE_INFO.SUPPLIER
     *
     * @mbggenerated
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MOBLE_INFO.SUPPLIER
     *
     * @param supplier the value for DATA_MOBLE_INFO.SUPPLIER
     *
     * @mbggenerated
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MOBLE_INFO.REGION_CODE
     *
     * @return the value of DATA_MOBLE_INFO.REGION_CODE
     *
     * @mbggenerated
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MOBLE_INFO.REGION_CODE
     *
     * @param regionCode the value for DATA_MOBLE_INFO.REGION_CODE
     *
     * @mbggenerated
     */
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode == null ? null : regionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MOBLE_INFO.CREATE_TIME
     *
     * @return the value of DATA_MOBLE_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MOBLE_INFO.CREATE_TIME
     *
     * @param createTime the value for DATA_MOBLE_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_MOBLE_INFO.UPDATE_TIME
     *
     * @return the value of DATA_MOBLE_INFO.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_MOBLE_INFO.UPDATE_TIME
     *
     * @param updateTime the value for DATA_MOBLE_INFO.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}
