ALTER TABLE `users`    ADD COLUMN `VIP_LEVEL` int(0) NULL DEFAULT 1 AFTER `STATUS`;
ALTER TABLE `users`    ADD COLUMN `MOBILE` varchar(20) NULL AFTER `VIP_LEVEL`;
ALTER TABLE `users`    ADD COLUMN `EMAIL` varchar(32) NULL AFTER `MOBILE`;
ALTER TABLE `users`    ADD COLUMN `GITEE_ACCOUNT` varchar(32) NULL AFTER `EMAIL`;